SUPABASE_URL = "https://xjmlbfoyvgrelvidlqjh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbWxiZm95dmdyZWx2aWRscWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNTc2MTEsImV4cCI6MjA3OTgzMzYxMX0.REANHA98xjACam0KYqezrb7vFbAQojY5XEMIXwF28F4"

[users.admin]
username = "Hozaifa"
password = "HozaifaIsTheBest"
role = "admin"   # this account can delete attendance logs

[users.viewer]
username = "player"
password = "DUEEEBASKETBALL"
role = "viewer"  # can view logs but not delete
